networks:
  ai_agents_net:
    driver: bridge

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: chat_db
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ai_agents_net
    healthcheck:
      test: mysqladmin ping -h localhost -u dev --password=dev
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 30s

  agent:
    build:
      context: .
      dockerfile: Dockerfile
      target: agent
    container_name: adk_agent
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_GENAI_USE_VERTEXAI=FALSE
    volumes:
      - ./src:/app/src
    networks:
      - ai_agents_net

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    container_name: streamlit_app
    restart: unless-stopped
    depends_on:
      agent:
        condition: service_started
      db:
        condition: service_healthy
    ports:
      - "8501:8501"
    environment:
      - MYSQL_HOSTS=db
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
      - MYSQL_DATABASE=chat_db
      - API_BASE_URL=http://agent:8000
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - ./src:/app/src
    networks:
      - ai_agents_net

volumes:
  mysql_data:
