networks:
  ai_agents_net:
    driver: bridge

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: chat_db
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ai_agents_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d chat_db"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 30s

  agent:
    build:
      context: .
      dockerfile: Dockerfile
      target: agent
    container_name: adk_agent
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_GENAI_USE_VERTEXAI=FALSE
    volumes:
      - ./src:/app/src
    networks:
      - ai_agents_net

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    container_name: streamlit_app
    restart: unless-stopped
    depends_on:
      agent:
        condition: service_started
      db:
        condition: service_healthy
    ports:
      - "8501:8501"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DATABASE=chat_db
      - API_BASE_URL=http://agent:8000
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - ./src:/app/src
    networks:
      - ai_agents_net

volumes:
  postgres_data:
